spring:
  application:
    name: Lab12PartC

app:
  config:
    application-name: Lab12PartCSpringConfiguration
    version: v1.1.1
    server-url: http://localhost:8080
    server-name: tomcat
    user-first-name: Saurab
    user-last-name: Ghimire
    user-user-name: sourrab
    user-password: 12345678
    countries:
      - Nepal
      - SriLanka
      - USA
