spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs544_examples?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: ERROR
    org:
      springframework: ERROR

